language: node_js
node_js:
- 14
services: mongodb
env:
  global:
  - DB_URL=mongodb://127.0.0.1:27017/
  - DB_NAME=whiskse
deploy:
  provider: heroku
  api_key:
    secure: SPIMiHeZ4rufZrATNX+sdLepGEzPGOWrZRNkXN5pATcYv6ZrlDvBDpk6E5MCWao+KgAfJr5eXpkn6BzvgEf/8w/8mQs5fnMN3c76utygvd0s14N5gSvSf+dM109Re2FeT6vD7dem5DESB65vM7ufTbdcIlElKRnyyDNZZG4nkt9EPwrKQ+Jo9/RQPFRWoqEj1KbdK9SN9NDA/+SXRovmoMRJyguqXfwXS+t8HwhvcJ9axwn4+GTX1+S9oIiBN1cERdEFjd7Ie27i+t0QP3sKbG0WL/9Df+whGoS1JIOhh0pP9zktTH4AYOTXXVpE+LjB/mOmTFqDKuAebYCUcKOU7PKvORzAZ3pNmNqJITAmlLf1oCzATH9z3y+cS0fJWFZ4IR/AZcJ/+W4+ZcMS8aLzZMEy1jmM/joy/EUsRK8NqPf6Z3mW0y+Owp5iPc7NVaGgOChsRi61XDMAlkaH0ZWYdNwXF7uDDJpQwBJ4uQXfawgbNpfbF+qDwoJaIYEhCK+2PQczMkaOzwE3IHwKRoTYto+wBicoU9wpUqTf27SBllOBzNkGlBIr3OeTZcIVFP/e1ADcky19qs5GT7PB9/VbJk8wh+ZGjruTN+oWpfq3JMx2znATmeBLPuFB9u/ROvFDfgxgVBFAdczFjcMAGiJ3WPriaej0YNW3+zqwz+WTvfo=
  app: whisk-store-api
  on:
    repo: stebunting/whisk-store-api
    branch: main
  skip_cleanup: 'true'
